import { nodejs } from "@here.build/eslint-configs";
import { fileURLToPath } from "node:url";
import path from "path";

// @ts-expect-error todo
// eslint-disable-next-line unicorn/no-negated-condition,unicorn/prefer-module
const dirname = typeof __dirname !== "undefined" ? __dirname : path.dirname(fileURLToPath(import.meta.url));

const legacyArrivalRules = {
  // Lisp interpreter/runtime code is intentionally dynamic and parser-shaped.
  // These are extraction-era lint debts; behavior is guarded by the package's
  // large test suite and should be refactored separately from substrate repair.
  "@typescript-eslint/no-explicit-any": "off",
  "@typescript-eslint/no-shadow": "off",
  "@typescript-eslint/no-this-alias": "off",
  "@typescript-eslint/no-unnecessary-condition": "off",
  "@typescript-eslint/no-unused-vars": "off",
  "@typescript-eslint/prefer-as-const": "off",
  "@typescript-eslint/prefer-nullish-coalescing": "off",
  "compat/compat": "off",
  "import-x/no-duplicates": "off",
  "import-x/no-unresolved": "off",
  "import-x/order": "off",
  "no-console": "off",
  "no-prototype-builtins": "off",
  "prefer-const": "off",
  "prettier/prettier": "off",
  "promise/always-return": "off",
  "regexp/no-dupe-characters-character-class": "off",
  "regexp/no-super-linear-backtracking": "off",
  "regexp/no-unused-capturing-group": "off",
  "regexp/no-useless-non-capturing-group": "off",
  "regexp/prefer-d": "off",
  "regexp/use-ignore-case": "off",
  "security/detect-non-literal-regexp": "off",
  "security/detect-possible-timing-attacks": "off",
  "security/detect-unsafe-regex": "off",
  "sonarjs/cognitive-complexity": "off",
  "sonarjs/concise-regex": "off",
  "sonarjs/function-return-type": "off",
  "sonarjs/generator-without-yield": "off",
  "sonarjs/no-all-duplicated-branches": "off",
  "sonarjs/no-dead-store": "off",
  "sonarjs/no-misleading-array-reverse": "off",
  "sonarjs/no-nested-assignment": "off",
  "sonarjs/no-nested-conditional": "off",
  "sonarjs/no-redundant-assignments": "off",
  "sonarjs/no-unused-collection": "off",
  "sonarjs/prefer-regexp-exec": "off",
  "sonarjs/prefer-single-boolean-return": "off",
  "sonarjs/public-static-readonly": "off",
  "sonarjs/reduce-initial-value": "off",
  "sonarjs/redundant-type-aliases": "off",
  "sonarjs/regex-complexity": "off",
  "sonarjs/slow-regex": "off",
  "sonarjs/updated-loop-counter": "off",
  "unicorn/catch-error-name": "off",
  "unicorn/consistent-existence-index-check": "off",
  "unicorn/consistent-function-scoping": "off",
  "unicorn/filename-case": "off",
  "unicorn/no-array-for-each": "off",
  "unicorn/no-array-reverse": "off",
  "unicorn/no-array-sort": "off",
  "unicorn/no-for-loop": "off",
  "unicorn/no-negated-condition": "off",
  "unicorn/no-thenable": "off",
  "unicorn/no-this-assignment": "off",
  "unicorn/no-useless-collection-argument": "off",
  "unicorn/no-useless-spread": "off",
  "unicorn/numeric-separators-style": "off",
  "unicorn/prefer-at": "off",
  "unicorn/prefer-code-point": "off",
  "unicorn/prefer-export-from": "off",
  "unicorn/prefer-native-coercion-functions": "off",
  "unicorn/prefer-regexp-test": "off",
  "unicorn/prefer-set-has": "off",
  "unicorn/prefer-spread": "off",
  "unicorn/prefer-string-raw": "off",
  "unicorn/prefer-switch": "off",
  "unicorn/prefer-ternary": "off",
  "unicorn/prefer-single-call": "off",
  "require-yield": "off",

  "@typescript-eslint/no-floating-promises": "off",
  "@typescript-eslint/no-unsafe-function-type": "off",
  "@typescript-eslint/prefer-optional-chain": "off",
  "@typescript-eslint/switch-exhaustiveness-check": "off",
  "import-x/export": "off",
  "import-x/first": "off",
  "import-x/newline-after-import": "off",
  "no-empty": "off",
  "no-fallthrough": "off",
  "no-secrets/no-secrets": "off",
  "no-useless-catch": "off",
  "no-var": "off",
  "prefer-spread": "off",
  "regexp/optimal-quantifier-concatenation": "off",
  "sonarjs/block-scoped-var": "off",
  "sonarjs/class-name": "off",
  "sonarjs/no-duplicated-branches": "off",
  "sonarjs/no-empty-collection": "off",
  "sonarjs/no-globals-shadowing": "off",
  "sonarjs/no-identical-functions": "off",
  "sonarjs/no-inverted-boolean-check": "off",
  "sonarjs/no-labels": "off",
  "sonarjs/no-unused-vars": "off",
  "sonarjs/no-useless-catch": "off",
  "unicorn/new-for-builtins": "off",
  "unicorn/no-lonely-if": "off",
  "unicorn/no-typeof-undefined": "off",
  "unicorn/prefer-default-parameters": "off",
  "unicorn/prefer-string-slice": "off",
  "unicorn/no-await-expression-member": "off",
  "sonarjs/no-alphabetical-sort": "off",
  "sonarjs/no-async-constructor": "off",
};

export default [
  {
    ignores: ["vendor/**", "vitest*.config.ts", "src/__tests__/**", "src/**/__tests__/**", "src/__benchmarks__/**", "**/*.test.ts", "**/*.spec.ts"],
  },
  ...nodejs,
  {
    files: ["src/**/*.ts"],
    languageOptions: {
      parserOptions: {
        projectService: true,
        tsconfigRootDir: dirname,
      },
    },
    rules: legacyArrivalRules,
  },
];
